//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace MquterELab_UITest.workflowsvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="workflowsvc.WorkflowService")]
    public interface WorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/DoWork", ReplyAction="urn:WorkflowService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/RetrieveActivities", ReplyAction="urn:WorkflowService/RetrieveActivitiesResponse")]
        System.IAsyncResult BeginRetrieveActivities(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> EndRetrieveActivities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/SaveWorkFlow", ReplyAction="urn:WorkflowService/SaveWorkFlowResponse")]
        System.IAsyncResult BeginSaveWorkFlow(string xmlcontent, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndSaveWorkFlow(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/ExecuteWorkflow", ReplyAction="urn:WorkflowService/ExecuteWorkflowResponse")]
        System.IAsyncResult BeginExecuteWorkflow(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndExecuteWorkflow(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/HelloWorld", ReplyAction="urn:WorkflowService/HelloWorldResponse")]
        System.IAsyncResult BeginHelloWorld(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/GetJobStatus", ReplyAction="urn:WorkflowService/GetJobStatusResponse")]
        System.IAsyncResult BeginGetJobStatus(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState);
        
        string EndGetJobStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/GetJobOuput", ReplyAction="urn:WorkflowService/GetJobOuputResponse")]
        System.IAsyncResult BeginGetJobOuput(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetJobOuput(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WorkflowService/SaveWorkflowToRegistry", ReplyAction="urn:WorkflowService/SaveWorkflowToRegistryResponse")]
        System.IAsyncResult BeginSaveWorkflowToRegistry(System.AsyncCallback callback, object asyncState);
        
        bool EndSaveWorkflowToRegistry(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkflowServiceChannel : MquterELab_UITest.workflowsvc.WorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveActivitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveActivitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveWorkFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveWorkFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteWorkflowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteWorkflowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetJobStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetJobStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetJobOuputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetJobOuputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveWorkflowToRegistryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveWorkflowToRegistryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkflowServiceClient : System.ServiceModel.ClientBase<MquterELab_UITest.workflowsvc.WorkflowService>, MquterELab_UITest.workflowsvc.WorkflowService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveActivitiesDelegate;
        
        private EndOperationDelegate onEndRetrieveActivitiesDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveActivitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveWorkFlowDelegate;
        
        private EndOperationDelegate onEndSaveWorkFlowDelegate;
        
        private System.Threading.SendOrPostCallback onSaveWorkFlowCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecuteWorkflowDelegate;
        
        private EndOperationDelegate onEndExecuteWorkflowDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteWorkflowCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetJobStatusDelegate;
        
        private EndOperationDelegate onEndGetJobStatusDelegate;
        
        private System.Threading.SendOrPostCallback onGetJobStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetJobOuputDelegate;
        
        private EndOperationDelegate onEndGetJobOuputDelegate;
        
        private System.Threading.SendOrPostCallback onGetJobOuputCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveWorkflowToRegistryDelegate;
        
        private EndOperationDelegate onEndSaveWorkflowToRegistryDelegate;
        
        private System.Threading.SendOrPostCallback onSaveWorkflowToRegistryCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WorkflowServiceClient() {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<RetrieveActivitiesCompletedEventArgs> RetrieveActivitiesCompleted;
        
        public event System.EventHandler<SaveWorkFlowCompletedEventArgs> SaveWorkFlowCompleted;
        
        public event System.EventHandler<ExecuteWorkflowCompletedEventArgs> ExecuteWorkflowCompleted;
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetJobStatusCompletedEventArgs> GetJobStatusCompleted;
        
        public event System.EventHandler<GetJobOuputCompletedEventArgs> GetJobOuputCompleted;
        
        public event System.EventHandler<SaveWorkflowToRegistryCompletedEventArgs> SaveWorkflowToRegistryCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MquterELab_UITest.workflowsvc.WorkflowService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginRetrieveActivities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveActivities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> MquterELab_UITest.workflowsvc.WorkflowService.EndRetrieveActivities(System.IAsyncResult result) {
            return base.Channel.EndRetrieveActivities(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveActivities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginRetrieveActivities(callback, asyncState);
        }
        
        private object[] OnEndRetrieveActivities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndRetrieveActivities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveActivitiesCompleted(object state) {
            if ((this.RetrieveActivitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveActivitiesCompleted(this, new RetrieveActivitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveActivitiesAsync() {
            this.RetrieveActivitiesAsync(null);
        }
        
        public void RetrieveActivitiesAsync(object userState) {
            if ((this.onBeginRetrieveActivitiesDelegate == null)) {
                this.onBeginRetrieveActivitiesDelegate = new BeginOperationDelegate(this.OnBeginRetrieveActivities);
            }
            if ((this.onEndRetrieveActivitiesDelegate == null)) {
                this.onEndRetrieveActivitiesDelegate = new EndOperationDelegate(this.OnEndRetrieveActivities);
            }
            if ((this.onRetrieveActivitiesCompletedDelegate == null)) {
                this.onRetrieveActivitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveActivitiesCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveActivitiesDelegate, null, this.onEndRetrieveActivitiesDelegate, this.onRetrieveActivitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginSaveWorkFlow(string xmlcontent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveWorkFlow(xmlcontent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Guid MquterELab_UITest.workflowsvc.WorkflowService.EndSaveWorkFlow(System.IAsyncResult result) {
            return base.Channel.EndSaveWorkFlow(result);
        }
        
        private System.IAsyncResult OnBeginSaveWorkFlow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xmlcontent = ((string)(inValues[0]));
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginSaveWorkFlow(xmlcontent, callback, asyncState);
        }
        
        private object[] OnEndSaveWorkFlow(System.IAsyncResult result) {
            System.Guid retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndSaveWorkFlow(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveWorkFlowCompleted(object state) {
            if ((this.SaveWorkFlowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveWorkFlowCompleted(this, new SaveWorkFlowCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveWorkFlowAsync(string xmlcontent) {
            this.SaveWorkFlowAsync(xmlcontent, null);
        }
        
        public void SaveWorkFlowAsync(string xmlcontent, object userState) {
            if ((this.onBeginSaveWorkFlowDelegate == null)) {
                this.onBeginSaveWorkFlowDelegate = new BeginOperationDelegate(this.OnBeginSaveWorkFlow);
            }
            if ((this.onEndSaveWorkFlowDelegate == null)) {
                this.onEndSaveWorkFlowDelegate = new EndOperationDelegate(this.OnEndSaveWorkFlow);
            }
            if ((this.onSaveWorkFlowCompletedDelegate == null)) {
                this.onSaveWorkFlowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveWorkFlowCompleted);
            }
            base.InvokeAsync(this.onBeginSaveWorkFlowDelegate, new object[] {
                        xmlcontent}, this.onEndSaveWorkFlowDelegate, this.onSaveWorkFlowCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginExecuteWorkflow(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteWorkflow(workflowName, workflowId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Guid MquterELab_UITest.workflowsvc.WorkflowService.EndExecuteWorkflow(System.IAsyncResult result) {
            return base.Channel.EndExecuteWorkflow(result);
        }
        
        private System.IAsyncResult OnBeginExecuteWorkflow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workflowName = ((string)(inValues[0]));
            System.Guid workflowId = ((System.Guid)(inValues[1]));
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginExecuteWorkflow(workflowName, workflowId, callback, asyncState);
        }
        
        private object[] OnEndExecuteWorkflow(System.IAsyncResult result) {
            System.Guid retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndExecuteWorkflow(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteWorkflowCompleted(object state) {
            if ((this.ExecuteWorkflowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteWorkflowCompleted(this, new ExecuteWorkflowCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteWorkflowAsync(string workflowName, System.Guid workflowId) {
            this.ExecuteWorkflowAsync(workflowName, workflowId, null);
        }
        
        public void ExecuteWorkflowAsync(string workflowName, System.Guid workflowId, object userState) {
            if ((this.onBeginExecuteWorkflowDelegate == null)) {
                this.onBeginExecuteWorkflowDelegate = new BeginOperationDelegate(this.OnBeginExecuteWorkflow);
            }
            if ((this.onEndExecuteWorkflowDelegate == null)) {
                this.onEndExecuteWorkflowDelegate = new EndOperationDelegate(this.OnEndExecuteWorkflow);
            }
            if ((this.onExecuteWorkflowCompletedDelegate == null)) {
                this.onExecuteWorkflowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteWorkflowCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteWorkflowDelegate, new object[] {
                        workflowName,
                        workflowId}, this.onEndExecuteWorkflowDelegate, this.onExecuteWorkflowCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginHelloWorld(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(workflowName, workflowId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MquterELab_UITest.workflowsvc.WorkflowService.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workflowName = ((string)(inValues[0]));
            System.Guid workflowId = ((System.Guid)(inValues[1]));
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginHelloWorld(workflowName, workflowId, callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync(string workflowName, System.Guid workflowId) {
            this.HelloWorldAsync(workflowName, workflowId, null);
        }
        
        public void HelloWorldAsync(string workflowName, System.Guid workflowId, object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, new object[] {
                        workflowName,
                        workflowId}, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginGetJobStatus(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetJobStatus(jobName, jobId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MquterELab_UITest.workflowsvc.WorkflowService.EndGetJobStatus(System.IAsyncResult result) {
            return base.Channel.EndGetJobStatus(result);
        }
        
        private System.IAsyncResult OnBeginGetJobStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobName = ((string)(inValues[0]));
            System.Guid jobId = ((System.Guid)(inValues[1]));
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginGetJobStatus(jobName, jobId, callback, asyncState);
        }
        
        private object[] OnEndGetJobStatus(System.IAsyncResult result) {
            string retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndGetJobStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetJobStatusCompleted(object state) {
            if ((this.GetJobStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetJobStatusCompleted(this, new GetJobStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetJobStatusAsync(string jobName, System.Guid jobId) {
            this.GetJobStatusAsync(jobName, jobId, null);
        }
        
        public void GetJobStatusAsync(string jobName, System.Guid jobId, object userState) {
            if ((this.onBeginGetJobStatusDelegate == null)) {
                this.onBeginGetJobStatusDelegate = new BeginOperationDelegate(this.OnBeginGetJobStatus);
            }
            if ((this.onEndGetJobStatusDelegate == null)) {
                this.onEndGetJobStatusDelegate = new EndOperationDelegate(this.OnEndGetJobStatus);
            }
            if ((this.onGetJobStatusCompletedDelegate == null)) {
                this.onGetJobStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetJobStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetJobStatusDelegate, new object[] {
                        jobName,
                        jobId}, this.onEndGetJobStatusDelegate, this.onGetJobStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginGetJobOuput(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetJobOuput(jobName, jobId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> MquterELab_UITest.workflowsvc.WorkflowService.EndGetJobOuput(System.IAsyncResult result) {
            return base.Channel.EndGetJobOuput(result);
        }
        
        private System.IAsyncResult OnBeginGetJobOuput(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobName = ((string)(inValues[0]));
            System.Guid jobId = ((System.Guid)(inValues[1]));
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginGetJobOuput(jobName, jobId, callback, asyncState);
        }
        
        private object[] OnEndGetJobOuput(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndGetJobOuput(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetJobOuputCompleted(object state) {
            if ((this.GetJobOuputCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetJobOuputCompleted(this, new GetJobOuputCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetJobOuputAsync(string jobName, System.Guid jobId) {
            this.GetJobOuputAsync(jobName, jobId, null);
        }
        
        public void GetJobOuputAsync(string jobName, System.Guid jobId, object userState) {
            if ((this.onBeginGetJobOuputDelegate == null)) {
                this.onBeginGetJobOuputDelegate = new BeginOperationDelegate(this.OnBeginGetJobOuput);
            }
            if ((this.onEndGetJobOuputDelegate == null)) {
                this.onEndGetJobOuputDelegate = new EndOperationDelegate(this.OnEndGetJobOuput);
            }
            if ((this.onGetJobOuputCompletedDelegate == null)) {
                this.onGetJobOuputCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetJobOuputCompleted);
            }
            base.InvokeAsync(this.onBeginGetJobOuputDelegate, new object[] {
                        jobName,
                        jobId}, this.onEndGetJobOuputDelegate, this.onGetJobOuputCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MquterELab_UITest.workflowsvc.WorkflowService.BeginSaveWorkflowToRegistry(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveWorkflowToRegistry(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool MquterELab_UITest.workflowsvc.WorkflowService.EndSaveWorkflowToRegistry(System.IAsyncResult result) {
            return base.Channel.EndSaveWorkflowToRegistry(result);
        }
        
        private System.IAsyncResult OnBeginSaveWorkflowToRegistry(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).BeginSaveWorkflowToRegistry(callback, asyncState);
        }
        
        private object[] OnEndSaveWorkflowToRegistry(System.IAsyncResult result) {
            bool retVal = ((MquterELab_UITest.workflowsvc.WorkflowService)(this)).EndSaveWorkflowToRegistry(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveWorkflowToRegistryCompleted(object state) {
            if ((this.SaveWorkflowToRegistryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveWorkflowToRegistryCompleted(this, new SaveWorkflowToRegistryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveWorkflowToRegistryAsync() {
            this.SaveWorkflowToRegistryAsync(null);
        }
        
        public void SaveWorkflowToRegistryAsync(object userState) {
            if ((this.onBeginSaveWorkflowToRegistryDelegate == null)) {
                this.onBeginSaveWorkflowToRegistryDelegate = new BeginOperationDelegate(this.OnBeginSaveWorkflowToRegistry);
            }
            if ((this.onEndSaveWorkflowToRegistryDelegate == null)) {
                this.onEndSaveWorkflowToRegistryDelegate = new EndOperationDelegate(this.OnEndSaveWorkflowToRegistry);
            }
            if ((this.onSaveWorkflowToRegistryCompletedDelegate == null)) {
                this.onSaveWorkflowToRegistryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveWorkflowToRegistryCompleted);
            }
            base.InvokeAsync(this.onBeginSaveWorkflowToRegistryDelegate, null, this.onEndSaveWorkflowToRegistryDelegate, this.onSaveWorkflowToRegistryCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MquterELab_UITest.workflowsvc.WorkflowService CreateChannel() {
            return new WorkflowServiceClientChannel(this);
        }
        
        private class WorkflowServiceClientChannel : ChannelBase<MquterELab_UITest.workflowsvc.WorkflowService>, MquterELab_UITest.workflowsvc.WorkflowService {
            
            public WorkflowServiceClientChannel(System.ServiceModel.ClientBase<MquterELab_UITest.workflowsvc.WorkflowService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginRetrieveActivities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RetrieveActivities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> EndRetrieveActivities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category> _result = ((System.Collections.ObjectModel.ObservableCollection<MQuter_eLabApp.TridentEmulatorSvc.Category>)(base.EndInvoke("RetrieveActivities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveWorkFlow(string xmlcontent, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = xmlcontent;
                System.IAsyncResult _result = base.BeginInvoke("SaveWorkFlow", _args, callback, asyncState);
                return _result;
            }
            
            public System.Guid EndSaveWorkFlow(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Guid _result = ((System.Guid)(base.EndInvoke("SaveWorkFlow", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExecuteWorkflow(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = workflowName;
                _args[1] = workflowId;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteWorkflow", _args, callback, asyncState);
                return _result;
            }
            
            public System.Guid EndExecuteWorkflow(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Guid _result = ((System.Guid)(base.EndInvoke("ExecuteWorkflow", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHelloWorld(string workflowName, System.Guid workflowId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = workflowName;
                _args[1] = workflowId;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetJobStatus(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = jobName;
                _args[1] = jobId;
                System.IAsyncResult _result = base.BeginInvoke("GetJobStatus", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetJobStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetJobStatus", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetJobOuput(string jobName, System.Guid jobId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = jobName;
                _args[1] = jobId;
                System.IAsyncResult _result = base.BeginInvoke("GetJobOuput", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetJobOuput(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetJobOuput", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveWorkflowToRegistry(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SaveWorkflowToRegistry", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveWorkflowToRegistry(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveWorkflowToRegistry", _args, result)));
                return _result;
            }
        }
    }
}
